### ISSUE TITLE
 show larger thumbnails is too larger

### ISSUE THREAD

**Issue by siroroe** [xuejianxianzun/PixivBatchDownloader#343] opened 2023-08-09 14:46 UTC
as the title， show larger thumbnails is too larger，too larger。

**Comment by xuejianxianzun** [comment] 2023-08-10 01:16
![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/8e4c3121-911a-493d-ae7d-2c12bdaf81bf)
This is not a bug.
After this function is enabled, the maximum size of the image displayed is 540x540px.
Images may appear larger due to system scaling that may be applied on some high resolution monitors.
You can reduce the zoom (`Ctrl` + `-`) on Pixiv, or turn it off in the downloader's "enhancements".

**Comment by SOPMOD2LuvRO** [comment] 2023-08-10 19:44
This IS a bug, the functionality of this recently broke and changed. The images now overlap when they did not before.
This is on a 1080p monitor, NOT a "high resolution" monitor, and this is definitely not system scaling.
<img width="465" alt="image" src="https://github.com/xuejianxianzun/PixivBatchDownloader/assets/90974500/bbab5c80-35d9-474f-a533-b82fb6e1291d">

**Comment by xuejianxianzun** [comment] 2023-08-11 01:40
> This IS a bug, the functionality of this recently broke and changed. The images now overlap when they did not before. This is on a 1080p monitor, NOT a "high resolution" monitor, and this is definitely not system scaling. <img alt="image" width="465" src="https://user-images.githubusercontent.com/90974500/259856829-bbab5c80-35d9-474f-a533-b82fb6e1291d.png">

![image](https://github.com/xuejianxianzun/PixivBatchDownloader/assets/17283977/c4b9eb9a-f3e2-4c74-bb83-f7eee3a9b779)
https://www.pixiv.net/en/artworks/109641604

This issue has been fixed, please check that your extension version is up to date.

**Comment by xuejianxianzun** [comment] 2023-08-11 01:43
> This IS a bug, the functionality of this recently broke and changed. The images now overlap when they did not before. This is on a 1080p monitor, NOT a "high resolution" monitor, and this is definitely not system scaling. <img alt="image" width="465" src="https://user-images.githubusercontent.com/90974500/259856829-bbab5c80-35d9-474f-a533-b82fb6e1291d.png">

Yes, there is a problem with the dark theme, you can turn off the dark theme first.
This issue will be fixed in the next update.

**Comment by xuejianxianzun** [comment] 2023-08-11 10:26
ver 16.1.2 updated.

**Closed by xuejianxianzun** 2023-08-11 10:26 UTC
Labels: wontfix
