### ISSUE TITLE
Duplicate Files [BUG]

### ISSUE THREAD

**Issue by Sorobou** [xuejianxianzun/PixivBatchDownloader#381] opened 2024-01-15 23:25 UTC
Hello,

Lately it is common that duplicate files won't be recognized and instead of skipped will just be replaced in the folder even though the file destination and naming rule is the same. Any ideas on how to correct this? Thank you.

[Powerful Pixiv Downloader Settings.json](https://github.com/xuejianxianzun/PixivBatchDownloader/files/13943683/Powerful.Pixiv.Downloader.Settings.json)

**Comment by xuejianxianzun** [comment] 2024-01-16 02:49
I didn't check this issue. Download this work twice, the downloader can skip it the second time:
https://www.pixiv.net/artworks/115213285

**Comment by Sorobou** [comment] 2024-01-16 22:15
> I didn't check this issue. Download this work twice, the downloader can skip it the second time: https://www.pixiv.net/artworks/115213285

Thanks for the reply. In the past it always worked, but now it almost always will not skip, not sure what else could be related. Downloads go to an encrypted drive if that matters.

**Comment by xuejianxianzun** [comment] 2024-01-24 05:02
Close this issues as I cannot reproduce the problem.

**Closed by xuejianxianzun** 2024-01-24 05:02 UTC
